# See docs: https://embarkstudios.github.io/cargo-deny/checks/index.html
# Some inspiration is drawn from: https://github.com/hyperium/tonic/blob/master/deny.toml

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
unsound = "deny"
ignore = [
    # error[unsound]: Potential unaligned read
    #   ┌─ /home/cornelius/projects/elastio/roxide/Cargo.lock:11:1
    #   │
    #11 │ atty 0.2.14 registry+https://github.com/rust-lang/crates.io-index
    #   │ ----------------------------------------------------------------- unsound advisory detected
    #   │
    #   = ID: RUSTSEC-2021-0145
    #   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0145
    #   = On windows, `atty` dereferences a potentially unaligned pointer.
    #
    #     In practice however, the pointer won't be unaligned unless a custom global allocator is used.
    #
    #     In particular, the `System` allocator on windows uses `HeapAlloc`, which guarantees a large enough alignment.
    #
    #     # atty is Unmaintained
    #
    #     A Pull Request with a fix has been provided over a year ago but the maintainer seems to be unreachable.
    #
    #     Last release of `atty` was almost 3 years ago.
    #
    #     ## Possible Alternative(s)
    #
    #     The below list has not been vetted in any way and may or may not contain alternatives;
    #
    #      - [is-terminal](https://crates.io/crates/is-terminal)
    #      - std::io::IsTerminal *nightly-only experimental*
    #   = Announcement: https://github.com/softprops/atty/issues/50
    #   = Solution: No safe upgrade is available!
    #   = atty v0.2.14
    #     └── clap v2.34.0
    #         └── structopt v0.3.26
    #             └── cheburashka v4.4.7
    #                 ├── elasyncio v3.1.0
    #                 │   └── roxide v5.2.3-dev
    #                 ├── roxide v5.2.3-dev (*)
    #                 └── try-again v2.1.2
    #                     └── roxide v5.2.3-dev (*)
    "RUSTSEC-2021-0145",

    #error[unsound]: const-cstr is Unmaintained
    #   ┌─ /home/cornelius/projects/elastio/roxide/Cargo.lock:34:1
    #   │
    #34 │ const-cstr 0.3.0 registry+https://github.com/rust-lang/crates.io-index
    #   │ ---------------------------------------------------------------------- unsound advisory detected
    #   │
    #   = ID: RUSTSEC-2023-0020
    #   = Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0020
    #   = Last release was about five years ago.
    #
    #     The maintainer(s) have been unreachable to respond to any issues that may or may not include security issues.
    #
    #     The repository is now archived and there is no security policy in place to contact the maintainer(s) otherwise.
    #
    #     No direct fork exist.
    #
    #     # const-cstr is Unsound
    #
    #     The crate violates the safety contract of [ffi::CStr::from_bytes_with_nul_unchecked](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked) used in `ConstCStr::as_cstr`
    #
    #     No interior nul bytes checking is done either by the constructor or the canonical macro to create the `ConstCStr`
    #
    #     # const-cstr Panic
    #
    #     Additionally the crate may cause runtime panics if statically compiled and ran with any untrusted data that is not nul-terminated.
    #
    #     This is however unlikely but the the crate should not be used for untrusted data in context where panic may create a DoS vector.
    #
    #     ## Possible Alternatives
    #
    #     The below may or may not provide alternative(s)
    #
    #     - [const_str::cstr!](https://docs.rs/const-str/latest/const_str/macro.cstr.html)
    #     - [cstr::cstr!](https://crates.io/crates/cstr)
    #   = Announcement: https://github.com/abonander/const-cstr
    #   = Solution: No safe upgrade is available!
    #   = const-cstr v0.3.0
    #     └── (dev) roxide-librocksdb-sys v5.2.3-dev
    #         ├── roxide v5.2.3-dev
    #         └── roxide-rocksdb v5.2.3-dev
    #             └── roxide v5.2.3-dev (*)
    "RUSTSEC-2023-0020",

    #error[unmaintained]: ansi_term is Unmaintained
    #  ┌─ /home/cornelius/projects/elastio/roxide/Cargo.lock:6:1
    #  │
    #6 │ ansi_term 0.12.1 registry+https://github.com/rust-lang/crates.io-index
    #  │ ---------------------------------------------------------------------- unmaintained advisory detected
    #  │
    #  = ID: RUSTSEC-2021-0139
    #  = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0139
    #  = The maintainer has advised that this crate is deprecated and will not receive any maintenance.
    #
    #    The crate does not seem to have much dependencies and may or may not be ok to use as-is.
    #
    #    Last release seems to have been three years ago.
    #
    #    ## Possible Alternative(s)
    #
    #     The below list has not been vetted in any way and may or may not contain alternatives;
    #
    #     - [anstyle](https://github.com/epage/anstyle)
    #     - [console](https://crates.io/crates/console)
    #     - [nu-ansi-term](https://crates.io/crates/nu-ansi-term)
    #     - [owo-colors](https://crates.io/crates/owo-colors)
    #     - [stylish](https://crates.io/crates/stylish)
    #     - [yansi](https://crates.io/crates/yansi)
    #
    #    ## Dependency Specific Migration(s)
    #
    #     - [structopt, clap2](https://github.com/clap-rs/clap/discussions/4172)
    #  = Announcement: https://github.com/ogham/rust-ansi-term/issues/72
    #  = Solution: No safe upgrade is available!
    #  = ansi_term v0.12.1
    #    └── clap v2.34.0
    #        └── structopt v0.3.26
    #            └── cheburashka v4.4.7
    #                ├── elasyncio v3.1.0
    #                │   └── roxide v5.2.3-dev
    #                ├── roxide v5.2.3-dev (*)
    #                └── try-again v2.1.2
    #                    └── roxide v5.2.3-dev (*)
    "RUSTSEC-2021-0139",

    #error[unmaintained]: yaml-rust is unmaintained.
    #    ┌─ /home/anshox/src/elastio/roxide/Cargo.lock:332:1
    #    │
    #332 │ yaml-rust 0.4.5 registry+https://github.com/rust-lang/crates.io-index
    #    │ --------------------------------------------------------------------- unmaintained advisory detected
    #    │
    #    = ID: RUSTSEC-2024-0320
    #    = Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0320
    #    = The maintainer seems [unreachable](https://github.com/chyh1990/yaml-rust/issues/197).
    #
    #      Many issues and pull requests have been submitted over the years
    #      without any [response](https://github.com/chyh1990/yaml-rust/issues/160).
    #
    #      ## Alternatives
    #
    #      Consider switching to the actively maintained `yaml-rust2` fork of the original project:
    #
    #      - [yaml-rust2](https://github.com/Ethiraric/yaml-rust2)
    #      - [yaml-rust2 @ crates.io](https://crates.io/crates/yaml-rust2))
    #    = Announcement: https://github.com/rustsec/advisory-db/issues/1921
    #    = Solution: No safe upgrade is available!
    #    = yaml-rust v0.4.5
    #      └── config v0.11.0
    #          └── try-again v2.1.3
    #              └── roxide v6.0.3-dev
    "RUSTSEC-2024-0320"
]

# The lint level for crates with security notices. Note that as of
# 2019-12-17 there are no security notice advisories in
# https://github.com/rustsec/advisory-db
notice = "deny"

# severity-threshold = "None" | "Low" | "Medium" | "High" | "Critical"

[bans]
# This lint issues false-positives for `{ path = "foo/bar" }` dependencies
# FIXME: make it "deny" once this bug is fixed:
# https://github.com/EmbarkStudios/cargo-deny/issues/241
wildcards = "allow"

multiple-versions = "deny"

# The skips are generated via the `deny.nu` script from here:
# https://www.notion.so/elastio/Cargo-deny-lints-4e3f11b310fe46bbba48caf64cceb3bf
skip = [
    # Comes from roxide-librocksdb-sys -> bindgen@0.65.1
    # Other direct parents:
    #   clap@2.34.0
    #   lexical-core@0.7.6
    #   procfs@0.14.2
    #   raw-cpuid@10.7.0
    #   redox_syscall@0.3.5
    #   redox_syscall@0.4.1
    #   rustix@0.36.16
    #   security-framework@2.9.2
    #   system-configuration@0.5.1
    { name = "bitflags", version = "=1.3.2" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: clap@2.34.0
    { name = "strsim", version = "=0.8.0" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: h2@0.3.21
    { name = "indexmap", version = "=1.9.3" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: windows-targets@0.42.2
    { name = "windows_i686_msvc", version = "=0.42.2" },
    { name = "windows_x86_64_gnu", version = "=0.42.2" },
    { name = "windows_i686_gnu", version = "=0.42.2" },
    { name = "windows_aarch64_msvc", version = "=0.42.2" },
    { name = "windows_x86_64_gnullvm", version = "=0.42.2" },
    { name = "windows_aarch64_gnullvm", version = "=0.42.2" },
    { name = "windows_x86_64_msvc", version = "=0.42.2" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: windows-targets@0.48.5
    { name = "windows_i686_msvc", version = "=0.48.5" },
    { name = "windows_x86_64_msvc", version = "=0.48.5" },
    { name = "windows_i686_gnu", version = "=0.48.5" },
    { name = "windows_aarch64_msvc", version = "=0.48.5" },
    { name = "windows_x86_64_gnullvm", version = "=0.48.5" },
    { name = "windows_aarch64_gnullvm", version = "=0.48.5" },
    { name = "windows_x86_64_gnu", version = "=0.48.5" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: procfs@0.14.2
    { name = "rustix", version = "=0.36.17" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: cheburashka@4.5.0, tracing-opentelemetry@0.17.4
    { name = "tracing-log", version = "=0.1.4" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: gethostname@0.4.3, parking_lot_core@0.9.9, windows-sys@0.48.0
    { name = "windows-targets", version = "=0.48.5" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: io-lifetimes@1.0.11, mio@0.8.11, tokio@1.37.0, winreg@0.50.0
    { name = "windows-sys", version = "=0.48.0" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: matchers@0.1.0
    { name = "regex-automata", version = "=0.1.10" },

    # Comes from roxide -> try-again@2.1.3
    # Direct parents: config@0.11.0
    { name = "nom", version = "=5.1.3" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: atty@0.2.14
    { name = "hermit-abi", version = "=0.1.19" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: rustix@0.36.16
    { name = "linux-raw-sys", version = "=0.1.4" },
    { name = "windows-sys", version = "=0.45.0" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: structopt-derive@0.4.18
    { name = "heck", version = "=0.3.3" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: indexmap@1.9.3
    { name = "hashbrown", version = "=0.12.3" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: regex-automata@0.1.10
    { name = "regex-syntax", version = "=0.6.29" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: pin-project@0.4.30
    { name = "pin-project-internal", version = "=0.4.30" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: windows-sys@0.45.0
    { name = "windows-targets", version = "=0.42.2" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: snafu@0.6.10
    { name = "pin-project", version = "=0.4.30" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents:
    #   pin-project-internal@0.4.30
    #   proc-macro-error@1.0.4
    #   quickcheck_macros@1.0.0
    #   snafu-derive@0.6.10
    #   structopt-derive@0.4.18
    #   strum_macros@0.24.3
    { name = "syn", version = "=1.0.109" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: opentelemetry@0.17.0
    { name = "dashmap", version = "=4.0.2" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: procfs@0.14.2
    { name = "rustix", version = "=0.36.16" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: reqwest@0.11.27, rustls-pemfile@1.0.4
    { name = "base64", version = "=0.21.7" },

    # Comes from roxide -> elasyncio@3.1.0
    # Direct parents: whoami@1.5.1
    { name = "redox_syscall", version = "=0.4.1" },
]
deny = []

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "https://dl.cloudsmith.io/basic/elastio/private/cargo/index.git",
    "https://cargo.cloudsmith.io/elastio/private/",
]
allow-git = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
private = { ignore = true }

# run `cargo deny list` to see which crates use which license
allow = [
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Unlicense",
    "Apache-2.0",
    "CC0-1.0",
    "Zlib",
    "ISC",
    "Unicode-DFS-2016",
]
deny = []
default = "deny"
allow-osi-fsf-free = "neither"

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.92

[[licenses.clarify]]
name = "stream-vbyte"
version = "0.3.2"
# This is in fact `Copyfree Open Innovation License` but it seems there is no SPDX expression for it
# https://bitbucket.org/marshallpierce/stream-vbyte-rust/src/master/LICENSE.txt
expression = "Unlicense"
license-files = [
    # license file hash was taken from the error message
    { path = "LICENSE.txt", hash = 0x508d93ea },
]

[[licenses.clarify]]
# This crate has a low-confidence license inference score (0.85), so clarifying manually...
# This PR should fix low-confidence score: https://github.com/briansmith/webpki/pull/128
# The maintainer just needs some time to pay attention to it
name = "webpki"
version = "0.21.3"
expression = "ISC"
license-files = [{ path = "LICENSE", hash = 0x001c7e6c }]

[[licenses.clarify]]
name = "ring"
version = "0.16.15"
# Copied this expression from the comment of Jake-Shadle (maintainer of cargo-deny)
# https://github.com/EmbarkStudios/cargo-deny/issues/110#issuecomment-576173641
# The issue under ring repo:
# https://github.com/briansmith/ring/issues/902
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

# Copied from https://github.com/hsivonen/encoding_rs/blob/b73366a/README.md#licensing
[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [{ path = "COPYRIGHT", hash = 0x39f8ad31 }]
