[registries.elastio-private]
credential-provider = "cargo:token"
index = "sparse+https://cargo.cloudsmith.io/elastio/private/"

# Temporary redirection for the period of the migration to the new repo address
# Should be removed once all dependent crates have been migrated to the new protocol.
[source.elastio-private-old]
registry = "https://dl.cloudsmith.io/basic/elastio/private/cargo/index.git"
replace-with = "elastio-private"
