[package]
name = "roxide"
version = "0.1.0"
authors = ["Adam Nelson <anelson@users.noreply.github.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elasyncio = { path = "../elasyncio" }
cheburashka = { path = "../cheburashka" }
cpp = "0.5"
futures = "0.3"
hex = "0.4"
json = "0.12"
lazy_static = "1.4"
libc = "0.2"
librocksdb-sys = { git = "https://github.com/elastio/rust-rocksdb", tag = "elastio-v6.11.4", default_features = false, features = ["lz4", "zstd"] }
log = "0.4" # Needed only for the log level enum
maplit = "1.0"
num-traits = "0.2"
once_cell = "1.5"
parking_lot = "0.11"
rocksdb = { git = "https://github.com/elastio/rust-rocksdb", tag = "elastio-v6.11.4", default_features = false, features = ["lz4", "zstd"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
smallvec = "1.5"
snafu = { version = "0.6", features = ["backtraces", "futures"] }
strum = "0.19"
strum_macros = "0.19"
tempfile = "3"
tracing = "0.1" # Hopefully can figure out how to avoid needing this

[dev-dependencies]
assert_matches = "1.4"
glob = "0.3.0"
more-asserts = "0.2"
num_cpus = "1"
quickcheck = "0.9"
quickcheck_macros = "0.9"
rand = { version = "0.7", features = ["small_rng"] }
tokio = { version = "0.2", features = ["full"] }
uuid = "0.8.1"
walkdir = "2.3.1"

[build-dependencies]
cpp_build = "0.5"
